### ISSUE TITLE
编译的smx插件无法生成csv文件

### ISSUE THREAD

**Issue by MybestFriendM** [huoji120/AI_Aimbot_Detecter#2]
可以给一份smx吗

**Comment by huoji120** [comment]
Linux还是Windows? Linux多半是权限不对 给目录rw权限就行。Windows的最好错误信息看看是什么。

**Comment by MybestFriendM** [comment]
> Linux还是Windows? Linux多半是权限不对 给目录rw权限就行。Windows的最好错误信息看看是什么。

感谢，已经搞定了

**Comment by huoji120** [comment]
别直接拿去用,这个要自己扩展写成mongodb(存储永久数据)+redis缓存(存储对局数据)对每个对局20个kill以上的player进行检测的,检测要放到flask 作为tensorflow服务器来处理 (笑
